parser: Fixed build with bison 3.2 (fixes #11)
Bison 3.2 added support for movable types, but this change broke our
build. Each type is now enclosed in YY_RVREF() macro. If you use
templated type with multiple arguments it must contain comma. This comma
is however parsed by preprocessor which thinks that we have passed
multiple arguments to the function-like macro. This results in error
like:

error: too many arguments provided to function-like macro invocation

or

error: macro "YY_RVREF" passed 2 arguments, but takes just 1

This workaround fixes the problem and we can now build our parser with
pre-3.2 and 3.2+ bison versions. Since we want to abandon flex+bison
anyway, we will just use this workaround for now.